server {
    listen 8000 default_server;
    listen [::]:8000 default_server;
    server_name _;
    root /srv/termux-repo/current;
    autoindex off;
    server_tokens off;

    location / {
        try_files $uri =404;
        add_header X-Content-Type-Options nosniff always;
        add_header Cache-Control "public, max-age=300" always;
    }

    location ~* \.(deb|gpg|asc|gz|xz)$ {
        try_files $uri =404;
        add_header X-Content-Type-Options nosniff always;
        add_header Cache-Control "public, max-age=3600" always;
    }
}
